import { readdirSync, readFileSync, statSync } from 'node:fs'
import path from 'node:path'
import { describe, expect, it } from 'vitest'

/**
 * Guards the direction rules from .claude/skills/persian-rtl-ui/SKILL.md §1.
 *
 * The app renders `dir="rtl"` for fa/ar, so a physical utility is a latent bug:
 * it silently keeps pointing at the physical left even though the layout has
 * flipped. The mechanical rewrite that introduced logical classes everywhere is
 * easy to undo one className at a time, and nothing else in the build fails when
 * that happens -- so it is pinned here.
 */

const RENDERER_ROOT = path.join(process.cwd(), 'src/renderer')

/**
 * Radix/Mantine `side`, `align` and `position` prop values ('left-start',
 * 'right-end', 'right-to-left'). Physical by contract, not Tailwind classes.
 */
const RADIX_SIDE_WORD = /^(?:left|right)-(?:start|end|align|to-left|to-right)$/

/** Physical utilities that must not appear in a className. */
const FORBIDDEN = [
  // margin / padding
  { re: /(?<![\w-])-?m[lr]-(?!auto\b)[\w[]/, label: 'ml-*/mr-* (use ms-*/me-*)' },
  { re: /(?<![\w-])-?p[lr]-[\w[]/, label: 'pl-*/pr-* (use ps-*/pe-*)' },
  // text alignment
  { re: /(?<![\w-])text-left\b/, label: 'text-start (use text-start)' },
  { re: /(?<![\w-])text-right\b/, label: 'text-end (use text-end)' },
  // inset position
  { re: /(?<![\w-])left-(?!1\/2\b|\[50%\])[\w[]/, label: 'left-* (use start-*)' },
  { re: /(?<![\w-])right-(?!full\b)[\w[]/, label: 'right-* (use end-*)' },
  // side borders and corners
  { re: /(?<![\w-])border-[lr](?:-|\b)/, label: 'border-s/r (use border-s/e)' },
  { re: /(?<![\w-])rounded-[lr](?:-|\b)/, label: 'rounded-s/r (use rounded-s/e)' },
  // sibling-margin hack that does not survive a direction flip
  { re: /(?<![\w-])space-x-/, label: 'space-x-* (use gap-*)' },
  // "fix RTL by reversing the row" -- flex already reads first-to-last
  { re: /(?<![\w-])flex-row-reverse\b/, label: 'flex-row-reverse (remove)' },
]

/**
 * Files where a physical class is correct by contract, with the reason.
 * Keyed by repo-relative path.
 */
const ALLOWED: Record<string, string> = {
  // Radix `side`/`align` prop values ('left-start', 'right-end'), not classes.
  'src/renderer/components/ui/tooltip.tsx': 'Radix Side type values',
  'src/renderer/components/common/MiniButton.tsx': 'Radix Side type values',
  // Markdown alignment directives: authored in LTR source, must round-trip.
  'src/renderer/components/markdown-text.tsx': '[[align=...]] markdown directives',
  // Physical centering: `left-1/2` paired with `-translate-x-1/2` inside a
  // fixed-width gutter, where a logical property would break the centering.
  // The desktop sidebar is physical too: its `side` prop is physical (it
  // drives `data-side` -> `rotate-180` and the resize rail) and the caller
  // already flips it per direction, so a logical class would read
  // "inline-start" and land the sidebar on the wrong edge.
  'src/renderer/components/ui/sidebar.tsx': 'left-1/2 centering + physical `side` prop',
  // Same reasoning for the mobile drawer, whose `side` is the physical
  // `Sidebar` `side` passed straight through to the Sheet.
  'src/renderer/components/ui/sheet.tsx': 'physical `side` variants (mobile sidebar drawer)',
  // The resize handle tracks the sidebar panel's physical edge.
  'src/renderer/Sidebar.tsx': 'resizer edge follows the physical sidebar side',
  // Generated inventory; regenerated by scripts/generate-ui-inventory.mjs.
  'src/renderer/dev/uiInventory.generated.ts': 'generated file',
  // Prose in test/story metadata ("classic left-aligned or bubble layout").
  'src/renderer/components/chat/Message.test.tsx': 'test name prose',
  'src/renderer/components/stories/CommonControlsReal.stories.tsx': 'story metadata prose',
  'src/renderer/routes/-new-user-scenarios/scenarios.ts': 'scenario fixture prose',
  // Embedded HTML/CSS strings for LTR artifacts and docs, not app chrome.
  'src/renderer/lib/format-chat.tsx': 'LTR artifact HTML fixture',
  'src/renderer/packages/initial_data.ts': 'seed conversation fixtures',
}

function walk(dir: string, out: string[] = []): string[] {
  for (const entry of readdirSync(dir)) {
    if (entry === 'node_modules' || entry === 'dist') continue
    const full = path.join(dir, entry)
    if (statSync(full).isDirectory()) walk(full, out)
    else if (/\.(tsx|ts)$/.test(entry)) out.push(full)
  }
  return out
}

/** Class-ish substrings are what we care about; pull them out of a line. */
function classTokens(line: string): string[] {
  return line.match(/[^\s"'`{}()]+/g) ?? []
}

/**
 * Drops comments so a class name quoted in prose ("a logical `end-0` here
 * would...") is not mistaken for a class name in a className.
 */
function stripComments(source: string): string {
  return source.replace(/\/\*[\s\S]*?\*\//g, '').replace(/(^|[^:])\/\/.*$/gm, '$1')
}

describe('rtl: physical Tailwind utilities', () => {
  const files = walk(RENDERER_ROOT).filter(
    // This file names every forbidden utility in its own rule table.
    (f) => !f.endsWith('rtl-logical-classes.test.ts')
  )

  it('has fixtures to scan', () => {
    expect(files.length).toBeGreaterThan(100)
  })

  it.each(files)('%s', (absPath) => {
    const relPath = path.relative(process.cwd(), absPath)
    const allowed = ALLOWED[relPath]

    const offenders: string[] = []
    readFileSync(absPath, 'utf8')
      .split('\n')
      .forEach((line, i) => {
        for (const token of classTokens(line)) {
          if (RADIX_SIDE_WORD.test(token)) continue
          for (const { re, label } of FORBIDDEN) {
            if (re.test(token)) {
              offenders.push(`  ${relPath}:${i + 1}  ${label}\n      ${token}`)
            }
          }
        }
      })

    if (offenders.length > 0 && allowed) return
    expect(offenders, offenders.join('\n')).toEqual([])
  })
})

describe('rtl: document-level direction', () => {
  it('sets dir on <html> so portalled overlays inherit it', () => {
    // Radix Portal (Sheet, Dialog, Tooltip, Menu, Select) appends to
    // document.body, which sits outside the app shell. A `dir` scoped to the
    // shell left every one of them rendering LTR under fa/ar.
    const source = readFileSync(path.join(RENDERER_ROOT, 'hooks/useAppTheme.ts'), 'utf8')
    expect(source).toMatch(/root\.setAttribute\('dir', isRTL\(language\)/)
  })

  it('exposes a single RTL language list', () => {
    const source = readFileSync(path.join(RENDERER_ROOT, 'i18n/locales.ts'), 'utf8')
    expect(source).toContain('export function isRTL(')
  })
})

describe('rtl: sidebar anchoring stays physical', () => {
  /**
   * The `side` prop of the desktop sidebar and of the Sheet that stands in for
   * it on mobile is *physical* — Sidebar.tsx passes "right" under fa/ar. The
   * in-flow spacer (the first flex child) then lands on the right too, so a
   * logical `start-0`/`end-0` on the panel resolves to the opposite physical
   * edge: the panel painted itself on top of the main content while the space
   * it had reserved sat empty on the other side.
   *
   * The rule above cannot catch this — a logical class is exactly what it asks
   * for — so the physical anchoring is pinned directly.
   */
  it.each([
    ['src/renderer/components/ui/sidebar.tsx', /side === "left"[\s\S]{0,240}?"left-0 group-data/],
    ['src/renderer/components/ui/sidebar.tsx', /"right-0 group-data-\[collapsible=offcanvas\]:right-/],
    ['src/renderer/components/ui/sheet.tsx', /left: "inset-y-0 left-0 h-full/],
    ['src/renderer/components/ui/sheet.tsx', /right:\s*\n?\s*"inset-y-0 right-0 h-full/],
  ])('%s anchors the panel physically (%#)', (relPath, pattern) => {
    const source = readFileSync(path.join(process.cwd(), relPath), 'utf8')
    expect(source).toMatch(pattern)
  })

  it.each(['src/renderer/components/ui/sidebar.tsx', 'src/renderer/components/ui/sheet.tsx'])(
    '%s keeps no logical inset on a physical side variant',
    (relPath) => {
      const source = stripComments(readFileSync(path.join(process.cwd(), relPath), 'utf8'))
      expect(source).not.toMatch(/["'`\s](?:start|end)-0\b/)
    }
  )

  it('keeps the nav rail in page direction so Persian labels sit after their icon', () => {
    // The rail used to be a `dir="ltr"` island, which put every leading icon on
    // the physical left of its Persian label. Latin-only fields keep the island;
    // an icon rail has no Latin run to protect.
    const source = readFileSync(path.join(RENDERER_ROOT, 'Sidebar.tsx'), 'utf8')
    expect(source).not.toMatch(/className="sidebar-(?:brand-row|action-list)"[^>]*\bdir=/)
  })
})
