import { readdirSync, readFileSync, statSync } from 'node:fs'
import path from 'node:path'
import { describe, expect, it } from 'vitest'

/**
 * Guards the direction rules from .claude/skills/persian-rtl-ui/SKILL.md §1.
 *
 * The app renders `dir="rtl"` for fa/ar, so a physical utility is a latent bug:
 * it silently keeps pointing at the physical left even though the layout has
 * flipped. The mechanical rewrite that introduced logical classes everywhere is
 * easy to undo one className at a time, and nothing else in the build fails when
 * that happens -- so it is pinned here.
 */

const RENDERER_ROOT = path.join(process.cwd(), 'src/renderer')

/**
 * Radix/Mantine `side`, `align` and `position` prop values ('left-start',
 * 'right-end', 'right-to-left'). Physical by contract, not Tailwind classes.
 */
const RADIX_SIDE_WORD = /^(?:left|right)-(?:start|end|align|to-left|to-right)$/

/** Physical utilities that must not appear in a className. */
const FORBIDDEN = [
  // margin / padding
  { re: /(?<![\w-])-?m[lr]-(?!auto\b)[\w[]/, label: 'ml-*/mr-* (use ms-*/me-*)' },
  { re: /(?<![\w-])-?p[lr]-[\w[]/, label: 'pl-*/pr-* (use ps-*/pe-*)' },
  // text alignment
  { re: /(?<![\w-])text-left\b/, label: 'text-start (use text-start)' },
  { re: /(?<![\w-])text-right\b/, label: 'text-end (use text-end)' },
  // inset position
  { re: /(?<![\w-])left-(?!1\/2\b|\[50%\])[\w[]/, label: 'left-* (use start-*)' },
  { re: /(?<![\w-])right-(?!full\b)[\w[]/, label: 'right-* (use end-*)' },
  // side borders and corners
  { re: /(?<![\w-])border-[lr](?:-|\b)/, label: 'border-s/r (use border-s/e)' },
  { re: /(?<![\w-])rounded-[lr](?:-|\b)/, label: 'rounded-s/r (use rounded-s/e)' },
  // sibling-margin hack that does not survive a direction flip
  { re: /(?<![\w-])space-x-/, label: 'space-x-* (use gap-*)' },
  // "fix RTL by reversing the row" -- flex already reads first-to-last
  { re: /(?<![\w-])flex-row-reverse\b/, label: 'flex-row-reverse (remove)' },
]

/**
 * Files where a physical class is correct by contract, with the reason.
 * Keyed by repo-relative path.
 */
const ALLOWED: Record<string, string> = {
  // `dir="ltr"` islands: brand wordmark, model/icon rail, API-token field.
  // These pin Latin glyph order regardless of the page direction.
  'src/renderer/Sidebar.tsx': 'dir="ltr" brand row + icon rail',
  // Radix `side`/`align` prop values ('left-start', 'right-end'), not classes.
  'src/renderer/components/ui/tooltip.tsx': 'Radix Side type values',
  'src/renderer/components/common/MiniButton.tsx': 'Radix Side type values',
  // Markdown alignment directives: authored in LTR source, must round-trip.
  'src/renderer/components/markdown-text.tsx': '[[align=...]] markdown directives',
  // Physical centering: `left-1/2` paired with `-translate-x-1/2` inside a
  // fixed-width gutter, where a logical property would break the centering.
  // The desktop sidebar is also physical: its `side` prop is physical (it
  // drives `data-side` -> `rotate-180` and the resize rail) and the caller
  // already flips it per direction, so a logical class would read
  // "inline-start" and land the sidebar on the wrong edge.
  'src/renderer/components/ui/sidebar.tsx': 'left-1/2 centering + physical `side` prop',
  // Generated inventory; regenerated by scripts/generate-ui-inventory.mjs.
  'src/renderer/dev/uiInventory.generated.ts': 'generated file',
  // Prose in test/story metadata ("classic left-aligned or bubble layout").
  'src/renderer/components/chat/Message.test.tsx': 'test name prose',
  'src/renderer/components/stories/CommonControlsReal.stories.tsx': 'story metadata prose',
  'src/renderer/routes/-new-user-scenarios/scenarios.ts': 'scenario fixture prose',
  // Embedded HTML/CSS strings for LTR artifacts and docs, not app chrome.
  'src/renderer/lib/format-chat.tsx': 'LTR artifact HTML fixture',
  'src/renderer/packages/initial_data.ts': 'seed conversation fixtures',
}

function walk(dir: string, out: string[] = []): string[] {
  for (const entry of readdirSync(dir)) {
    if (entry === 'node_modules' || entry === 'dist') continue
    const full = path.join(dir, entry)
    if (statSync(full).isDirectory()) walk(full, out)
    else if (/\.(tsx|ts)$/.test(entry)) out.push(full)
  }
  return out
}

/** Class-ish substrings are what we care about; pull them out of a line. */
function classTokens(line: string): string[] {
  return line.match(/[^\s"'`{}()]+/g) ?? []
}

describe('rtl: physical Tailwind utilities', () => {
  const files = walk(RENDERER_ROOT).filter(
    // This file names every forbidden utility in its own rule table.
    (f) => !f.endsWith('rtl-logical-classes.test.ts')
  )

  it('has fixtures to scan', () => {
    expect(files.length).toBeGreaterThan(100)
  })

  it.each(files)('%s', (absPath) => {
    const relPath = path.relative(process.cwd(), absPath)
    const allowed = ALLOWED[relPath]

    const offenders: string[] = []
    readFileSync(absPath, 'utf8')
      .split('\n')
      .forEach((line, i) => {
        for (const token of classTokens(line)) {
          if (RADIX_SIDE_WORD.test(token)) continue
          for (const { re, label } of FORBIDDEN) {
            if (re.test(token)) {
              offenders.push(`  ${relPath}:${i + 1}  ${label}\n      ${token}`)
            }
          }
        }
      })

    if (offenders.length > 0 && allowed) return
    expect(offenders, offenders.join('\n')).toEqual([])
  })
})

describe('rtl: document-level direction', () => {
  it('sets dir on <html> so portalled overlays inherit it', () => {
    // Radix Portal (Sheet, Dialog, Tooltip, Menu, Select) appends to
    // document.body, which sits outside the app shell. A `dir` scoped to the
    // shell left every one of them rendering LTR under fa/ar.
    const source = readFileSync(path.join(RENDERER_ROOT, 'hooks/useAppTheme.ts'), 'utf8')
    expect(source).toMatch(/root\.setAttribute\('dir', isRTL\(language\)/)
  })

  it('exposes a single RTL language list', () => {
    const source = readFileSync(path.join(RENDERER_ROOT, 'i18n/locales.ts'), 'utf8')
    expect(source).toContain('export function isRTL(')
  })
})
